### ISSUE TITLE
Add support for Milvus vector DB

### ISSUE THREAD

**Issue by Pablo1785** [sobelio/llm-chain#146]
Milvus has recently published a repo and a crate for their official Rust SDK https://github.com/milvus-io/milvus-sdk-rust

**Comment by AmineDiro** [comment]
Hello,
I would love to contribute to this project and this issue. I have some experience working with Milvus in both Python and GO, I see that you support qdrant as a vector store  for now. As I can see from the `qdrant` implementation, all the collection creation details are given to the user (embedding_dim size, distance, index type ... ) and the `Qdrant` struct only has the client instance. Should the `Milvus` offer the same flexibility or hide the collection creation details, the index type, etc... from the the user ? Thanks for your answers 🤔
