### ISSUE TITLE
llm_chain_local: FieldRequiredError on example

### ISSUE THREAD

**Issue by leonardohn** [sobelio/llm-chain#147]
Running the [simple](https://github.com/sobelio/llm-chain/blob/main/crates/llm-chain-local/examples/simple.rs) example from `llm-chain-local` with the suggested command gives me the following error message:

```
Error: FieldRequiredError("model_type")
```

I also tried using `OptionsBuilder` manually and got the following error message:

```
Error: FieldRequiredError("Default field missing")
```

How can I properly use a LLaMa model with this library?

**Comment by williamhogman** [comment]
Hey thanks for reporting this seems like a bug with the new options system looking into it

**Comment by williamhogman** [comment]
Fixed in 0.12.1

**Comment by melMass** [comment]
Hey @williamhogman I'm still getting this on 0.12.2:
```ruby
["target\\release\\chat.exe", "llama", "G:/MODELS/LLM/models/nous-4bit-32g.bin", "Explain math"]
model_type: "llama"
model_path: "G:/MODELS/LLM/models/nous-4bit-32g.bin"
prompt: "Explain math"
Error: FieldRequiredError("Default field missing")
```

I initially thought it might be due to the model itself, but it works fine in llm-cli


```console
❯ llm llama infer -m "G:/MODELS/LLM/models/nous-4bit-32g.bin" -p "Rust is a cool programming language because"
✓ Loaded 363 tensors (10.2 GB) after 96ms
Rust is a cool programming language because of its focus on safety, speed and preventing data races. However the syntax can be intimidating for beginners - so here's an interactive tutorial to help you get started with Rust!
```

**Comment by melMass** [comment]
Adding `.with_options(&DEFAULT_OPTIONS)` here https://github.com/sobelio/llm-chain/blob/df531b14dfa68d4703a03778423598012314d5d8/crates/llm-chain-local/src/executor.rs#L58 fixed the issue for me

**Comment by williamhogman** [comment]
Okay great that you looked into it we will fix ASAP

**Comment by sherodtaylor** [comment]
This issue just came up again?
