### ISSUE TITLE
Run tests on Windows x86 and MacOs x86 in Github actions

### ISSUE THREAD

**Issue by williamhogman** [sobelio/llm-chain#24]

**Comment by SpirosMakris** [comment]
I have a Windows 10 machine. How can I help with this? Just run the tests and report output?

**Comment by williamhogman** [comment]
Hey so this is for GitHub actions :)

**Comment by SpirosMakris** [comment]
Ooops, did not read title. Sorry about this.

**Comment by williamhogman** [comment]
Haha, no I edited the title ;)
