### ISSUE TITLE
Some typo?

### ISSUE THREAD

**Issue by katopz** [sobelio/llm-chain#3]
Refer to https://github.com/sobelio/llm-chain/blob/78c2bdaf41aa6a76e8b4c9c22ab24d3a74567869/docs/README.md?plain=1#L20

I willing to make a PR for the fix but I'm not sure this is intend or just a typo 😅

<img width="667" alt="image" src="https://user-images.githubusercontent.com/97060/230703840-cf392a64-cdd4-44a3-8b87-a34be6a06b60.png">

**Comment by williamhogman** [comment]
Yes certainly a mistake. It is even supposed to say "personalised greeting". Feel free to create a PR
