### ISSUE TITLE
Panic when MessagePromptTemplate contains unbounded parameters.

### ISSUE THREAD

**Issue by ssoudan** [sobelio/llm-chain#33]
Hi, 

I'm trying to use your framework but having some issues with the templated prompt. 
Basically the issue is the LM is generating code that sometime contains '{}' or '{something}' and they get interpreted as unbounded named parameters during the `format()` in `template::apply_formatting()`.

Not sure what is the best way to address it. Don't see a use-case for having placeholders in what the 'Assistant' is returning (might be missing it). Was thinking of something like an `enum` with two variants, one being a template, not the other one. What do you think? 

Thanks,
Sebastien

----

Here is a pair of tests to reproduce the issue (only the second one fails). 

In the context of `llm-chain-openai/src/chatgpt/prompt.rs`: 
```rust
#[cfg(test)]
mod tests {

    #[test]
    fn test_chat_prompt_template() {
        use super::*;
        use async_openai::types::Role;
        let system_msg = MessagePromptTemplate::new(
            Role::System,
            "You are an assistant that speaks like Shakespeare.".into(),
        );
        let user_msg = MessagePromptTemplate::new(Role::User, "tell me a joke".into());

        let chat_template = ChatPromptTemplate::new(vec![system_msg, user_msg]);
        let messages = chat_template.format(&Parameters::new());
        assert_eq!(messages.len(), 2);
        assert_eq!(messages[0].role, Role::System);
        assert_eq!(
            messages[0].content,
            "You are an assistant that speaks like Shakespeare."
        );
        assert_eq!(messages[1].role, Role::User);
        assert_eq!(messages[1].content, "tell me a joke");
    }

    #[test]
    fn test_chat_prompt_template_with_named_parameters() {
        use super::*;
        use async_openai::types::Role;
        let system_msg = MessagePromptTemplate::new(
            Role::System,
            "You are an assistant that speaks like Shakespeare.".into(),
        );
        let user_msg = MessagePromptTemplate::new(Role::User, "tell me a joke".into());
        let assistant_msg = MessagePromptTemplate::new(
            Role::User,
            "here is one, I'm sure, will crack you {up}".into(),
        );

        let chat_template = ChatPromptTemplate::new(vec![system_msg, user_msg, assistant_msg]);
        let messages = chat_template.format(&Parameters::new());
        assert_eq!(messages.len(), 2);
        assert_eq!(messages[0].role, Role::System);
        assert_eq!(
            messages[0].content,
            "You are an assistant that speaks like Shakespeare."
        );
        assert_eq!(messages[1].role, Role::User);
        assert_eq!(messages[1].content, "tell me a joke");
        assert_eq!(messages[2].role, Role::Assistant);
        assert_eq!(
            messages[2].content,
            "here is one, I'm sure, will crack you {up}"
        );
    }
}
```

**Comment by williamhogman** [comment]
>Not sure what is the best way to address it. Don't see a use-case for having placeholders in what the 'Assistant' is returning (might be missing it). Was thinking of something like an enum with two variants, one being a template, not the other one. What do you think?

I think this may be the right solution or possibly that we should offer some kind of escaping.

So just to understand the problem you are facing is that you are feeding the assistant's output back into your prompt (i.e. a sliding context window). Because we currently force you to use `PromptTemplate`  any `{}` that the model writes get interpreted as variables?

**Comment by ssoudan** [comment]
Yup and '{variable}' too.

**Comment by williamhogman** [comment]
Fixed will cut a release soon
