### ISSUE TITLE
Prompt formatting, parameters, and dynformat

### ISSUE THREAD

**Issue by DMJ16** [sobelio/llm-chain#83]
~Flagging that I'm noticing certain "messy" prompts where there's lots of unformatted context being injected into a user prompt is producing an error during prompt formatting. dynformat crate throws in the seq chain example and in simple (no chain) below. 
After seeing the error below, if i add `parameters!("name")` and rerun, then the same prompt will not throw an error.~

Noticing the issue when dynamic context contains a word wrapped in `{}`. I believe this is intended behavior so perhaps calling apps should format context injections etc or maybe this could be handled in lib.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExecutorError(PromptTemplateError(PromptTemplateError(LegacyTemplateError("missing argument: name"))))'`

**Comment by williamhogman** [comment]
Good catch. There is a method called `PromptTemplate::static_string` that can be used when using model inputs in your prompt template

**Comment by williamhogman** [comment]
Closing this one as the new prompt system should be able to handle this type of use case
